

### Publish a book
### TODO chnage the book id to something that exists in your DB and the publisherID to one that exists on your local
### instance of the publishing service
POST /books/10016/commands/publish HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "publisherId": "6b4ca9c9-b3ae-4130-b3f8-2da873c3940e"
}

